on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  dog_food_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
#      id: hello
      with:
        yaml-path: test.yaml