on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  dogfooding-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: verify test.yaml
      uses: ./
      with:
        args: test/test.yaml
  dogfooding-directory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: verify yaml directory
      uses: ./
      with:
        args: -d test