on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  dogfooding:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        yaml-path: test.yaml